apiVersion: v1
kind: Service
metadata:
  name: iperf
  labels:
    name: iperf
    app: iperf
spec:
  selector:
     app: iperf
  type: NodePort
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP

